version: '3.8'

services:
  db:
    build: postgres
    image: postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/pamps_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DBS=mlflow_db
      - POSTGRES_USER=mlflow_user
      - POSTGRES_PASSWORD=mlflow_password

  mlflow:
    build:
      context: .
    ports:
      - "${MLFLOW_PORT}:5000"
    environment:
      MLFLOW_TRACKING_URI: postgresql://mlflow_user:mlflow_password@db:5432/mlflow_db
    volumes:
      - "${MLFLOW_LOCAL_VOLUME}:/mlflow"
    depends_on:
      - db

volumes:
  postgres-data:
